name: 'Remove PR Labels'
description: 'Remove labels of a Pull Request on GitHub'
inputs:
  GITHUB_TOKEN:
    description: 'A GitHub token.'
    required: false
    default: ${{ github.token }}
  LABELS:
    description: 'An array of labels to remove, separated by commas. If not specified, all labels will be removed from the issue.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.LABELS }}
